jobs:
  build-linux-aarch64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - continue-on-error: true
      id: runcmd
      name: Run commands
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        run: 'apt update && apt install openjdk-8-jdk g++ -y

          ./mvnw package -pl common,arthas-vmtool

          cp arthas-vmtool/target/libArthas* lib/

          '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: arthas-vmtool/target/libArthas*
  build-linux-x64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw package
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: arthas-vmtool/target/libArthasJniLibrary-x64.so
  build-mac:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw package
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: arthas-vmtool/target/libArthas*
  build-windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw package
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: lib
        path: arthas-vmtool/target/*.dll
  commit_vmtool_files:
    needs:
    - build-linux-x64
    - build-linux-aarch64
    - build-mac
    - build-windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Upstream Repo
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: lib
        path: tmplib
    - continue-on-error: true
      name: Display structure of downloaded files
      run: ls -R
      working-directory: tmplib
    - continue-on-error: true
      name: Commit files
      run: 'git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git config --local user.name "github-actions[bot]"

        mv tmplib/* lib/

        git add lib/

        git commit -m "update arthas vmtool lib"

        '
    - continue-on-error: true
      name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: build vmtool
on:
  repository_dispatch:
    types: trigger-ga___build-vmtool.yaml
