jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package -P full
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/')
      name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'packaging/target/*.zip

          packaging/target/*.deb

          packaging/target/*.rpm

          tunnel-server/target/*fatjar.jar

          '
name: release
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
