jobs:
  macos_build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -P full
    strategy:
      matrix:
        java:
        - 8
        - 11
        os:
        - macos-latest
        - macos-14
  ubuntu_build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -P full
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 19
  windows_build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean install -P full
    strategy:
      matrix:
        java:
        - 8
        - 11
name: JavaCI
on:
  repository_dispatch:
    types: trigger-ga___test.yaml
